# Flight Price Datasets

1. Load the Flight Price dataset into a Pandas DataFrame and display the first
five rows.

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Data_Train.xlsx - Sheet1 (1).csv")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

2. Find the number of rows and columns in the dataset.

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Data_Train.xlsx - Sheet1 (1).csv")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

3. Display all column names in the dataset.

In [5]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

4. Display the data types of all columns.

In [7]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

5. Use df.info() to inspect the structure of the dataset.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

6. Check the number of missing values in each column.

In [9]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

7. Check the percentage of missing values in each column.

In [11]:
df.isnull().sum().mean()*100

18.181818181818183

8. Display the unique values and frequency of each value in the Airline column.

In [13]:
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

9. Display the frequency distribution of Total_Stops, including missing values.

In [14]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

10.Convert Date_of_Journey into a datetime format.

In [15]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], errors="coerce")
df["Date_of_Journey"]

C:\Users\harit\AppData\Local\Temp\ipykernel_17884\3309533516.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], errors="coerce")

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

11.Extract the day from Date_of_Journey and create a day column.

In [28]:
df = pd.DataFrame({'date':['2024-01-15', '2024-02-20', '2024-03-25']})
df["Days"] = df['date'].str.split("-").str[2]
df["Days"]

0    15
1    20
2    25
Name: Days, dtype: object

12.Extract the month from Date_of_Journey and create a month column.

In [29]:
df = pd.DataFrame({'date':['2024-01-15', '2024-02-20', '2024-03-25']})
df["Months"] = df['date'].str.split("-").str[1]
df["Months"]

0    01
1    02
2    03
Name: Months, dtype: object

13.Extract the year from Date_of_Journey and create a year column.

In [30]:
df = pd.DataFrame({'date':['2024-01-15', '2024-02-20', '2024-03-25']})
df["Year"] = df['date'].str.split("-").str[0]
df["Year"]

0    2024
1    2024
2    2024
Name: Year, dtype: object

In [37]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Data_Train.xlsx - Sheet1 (1).csv")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

14.Drop the original Date_of_Journey column after extracting the required
features.

In [39]:
df.drop("Date_of_Journey", axis=1,inplace=True)
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

15.Convert Dep_Time into datetime format and extract the departure hour into
Dep_Hour.

In [41]:
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], format='%H:%M')
df['Dep_Hour'] = df['Dep_Time'].dt.hour
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,1900-01-01 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,22
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,1900-01-01 05:50:00,13:15,7h 25m,2 stops,No info,7662,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,1900-01-01 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1900-01-01 18:05:00,23:30,5h 25m,1 stop,No info,6218,18
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1900-01-01 16:50:00,21:35,4h 45m,1 stop,No info,13302,16
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,1900-01-01 19:55:00,22:25,2h 30m,non-stop,No info,4107,19
10679,Air India,Kolkata,Banglore,CCU → BLR,1900-01-01 20:45:00,23:20,2h 35m,non-stop,No info,4145,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,1900-01-01 08:20:00,11:20,3h,non-stop,No info,7229,8
10681,Vistara,Banglore,New Delhi,BLR → DEL,1900-01-01 11:30:00,14:10,2h 40m,non-stop,No info,12648,11
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,1900-01-01 10:55:00,19:15,8h 20m,2 stops,No info,11753,10

16.Extract the departure minute from Dep_Time and create Dep_Minute.

In [46]:
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'])
df['Dep_Minute'] = df['Dep_Time'].dt.minute
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,1900-01-01 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,1900-01-01 05:50:00,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,1900-01-01 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1900-01-01 18:05:00,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1900-01-01 16:50:00,21:35,4h 45m,1 stop,No info,13302,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,1900-01-01 19:55:00,22:25,2h 30m,non-stop,No info,4107,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,1900-01-01 20:45:00,23:20,2h 35m,non-stop,No info,4145,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,1900-01-01 08:20:00,11:20,3h,non-stop,No info,7229,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,1900-01-01 11:30:00,14:10,2h 40m,non-stop,No info,12648,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,1900-01-01 10:55:00,19:15,8h 20m,2 stops,No info,11753,10,55

17.Drop the original Dep_Time column after extracting the required features.

In [47]:
df.drop("Dep_Time", axis=1,inplace=True)
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,16,50
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,10,55

18.Extract only the time portion from Arrival_Time.

In [53]:
df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce').dt.time
df['Arrival_Time']

0       NaT
1       NaT
2       NaT
3       NaT
4       NaT
         ..
10678   NaT
10679   NaT
10680   NaT
10681   NaT
10682   NaT
Name: Arrival_Time, Length: 10683, dtype: datetime64[ns]

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Data_Train.xlsx - Sheet1 (1).csv")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

In [5]:
df['Arrival_Time'] = df['Arrival_Time'].str.split().str[0]
df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_Minute'] = df['Arrival_Time'].str.split(':').str[1].astype(int)
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_Hour,Arrival_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,22,25
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,23,20
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,11,20
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,14,10
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,19,15

20.Drop the original Arrival_Time column after extracting the required features.

In [7]:
df.drop("Arrival_Time", axis=1)
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_Hour,Arrival_Minute,Duration_Hour
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,1,10,2.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,13,15,7.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,4,25,19.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,23,30,5.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,21,35,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,22,25,2.0
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,23,20,2.0
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,11,20,3.0
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,14,10,2.0
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,19,15,8.0

21.Extract the hour component from Duration and create Duration_Hour. Handle
invalid or missing extracted values appropriately.

In [6]:
df['Duration_Hour']=df['Duration'].astype(str).str.split("h").str[0]
df['Duration_Hour']=pd.to_numeric(df['Duration_Hour'],errors='coerce')
df['Duration_Hour']

0         2.0
1         7.0
2        19.0
3         5.0
4         4.0
         ...
10678     2.0
10679     2.0
10680     3.0
10681     2.0
10682     8.0
Name: Duration_Hour, Length: 10683, dtype: float64

22.Extract the minute component from Duration and create Duration_Minute.
Handle invalid or missing extracted values appropriately.

In [8]:
df["Duration_Minute"] = pd.to_numeric(df["Duration"].str.split().str[1].str.replace("m", ""),errors="coerce")
df["Duration_Minute"]

0        50.0
1        25.0
2         NaN
3        25.0
4        45.0
         ...
10678    30.0
10679    35.0
10680     NaN
10681    40.0
10682    20.0
Name: Duration_Minute, Length: 10683, dtype: float64

23.Drop the original Duration column after creating the numerical duration
features.

In [9]:
df.drop("Duration",axis=1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Total_Stops,Additional_Info,Price,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10,non-stop,No info,3897,1,10,2.0,50.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,2 stops,No info,7662,13,15,7.0,25.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,2 stops,No info,13882,4,25,19.0,NaN
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,1 stop,No info,6218,23,30,5.0,25.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,1 stop,No info,13302,21,35,4.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,non-stop,No info,4107,22,25,2.0,30.0
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,non-stop,No info,4145,23,20,2.0,35.0
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,non-stop,No info,7229,11,20,3.0,NaN
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,non-stop,No info,12648,14,10,2.0,40.0
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,2 stops,No info,11753,19,15,8.0,20.0

24.Replace non-stop in Total_Stops with 0 stops.

In [10]:
df["Total_Stops"]=df["Total_Stops"].replace("non-stop",0)
df["Total_Stops"]

0              0
1        2 stops
2        2 stops
3         1 stop
4         1 stop
          ...
10678          0
10679          0
10680          0
10681          0
10682    2 stops
Name: Total_Stops, Length: 10683, dtype: object

25.Extract only the numerical value from Total_Stops and convert the column into
an integer data type. Handle missing or invalid values appropriately.

In [11]:
df["Total_Stops"] = pd.to_numeric(df["Total_Stops"].astype(str).str.split().str[0],errors="coerce")
df["Total_Stops"] = df["Total_Stops"].fillna(0).astype(int)
df["Total_Stops"]

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10683, dtype: int32

27.Identify the missing values created in Route_3, Route_4, and Route_5 after
splitting the route.

In [13]:
df[["Route_3", "Route_4", "Route_5"]].isnull().sum()

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64

28.Replace the missing values in the route columns with an appropriate value
such as None.

In [14]:
df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]] = (df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]].fillna("None"))
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,0,No info,3897,1,10,2.0,50.0,BLR,DEL,None,None,None
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2,No info,7662,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2,No info,13882,4,25,19.0,NaN,DEL,LKO,BOM,COK,None
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1,No info,6218,23,30,5.0,25.0,CCU,NAG,BLR,None,None
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1,No info,13302,21,35,4.0,45.0,BLR,NAG,DEL,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,0,No info,4107,22,25,2.0,30.0,CCU,BLR,None,None,None
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,0,No info,4145,23,20,2.0,35.0,CCU,BLR,None,None,None
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,0,No info,7229,11,20,3.0,NaN,BLR,DEL,None,None,None
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,0,No info,12648,14,10,2.0,40.0,BLR,DEL,None,None,None
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2,No info,11753,19,15,8.0,20.0,DEL,GOI,BOM,COK,None

29.Drop the original Route column after creating and cleaning the route features.

In [15]:
df.drop("Route",axis=1,inplace=True)
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10,2h 50m,0,No info,3897,1,10,2.0,50.0,BLR,DEL,None,None,None
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2,No info,7662,13,15,7.0,25.0,CCU,IXR,BBI,BLR,None
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25,19h,2,No info,13882,4,25,19.0,NaN,DEL,LKO,BOM,COK,None
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1,No info,6218,23,30,5.0,25.0,CCU,NAG,BLR,None,None
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1,No info,13302,21,35,4.0,45.0,BLR,NAG,DEL,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,19:55,22:25,2h 30m,0,No info,4107,22,25,2.0,30.0,CCU,BLR,None,None,None
10679,Air India,27/04/2019,Kolkata,Banglore,20:45,23:20,2h 35m,0,No info,4145,23,20,2.0,35.0,CCU,BLR,None,None,None
10680,Jet Airways,27/04/2019,Banglore,Delhi,08:20,11:20,3h,0,No info,7229,11,20,3.0,NaN,BLR,DEL,None,None,None
10681,Vistara,01/03/2019,Banglore,New Delhi,11:30,14:10,2h 40m,0,No info,12648,14,10,2.0,40.0,BLR,DEL,None,None,None
10682,Air India,9/05/2019,Delhi,Cochin,10:55,19:15,8h 20m,2,No info,11753,19,15,8.0,20.0,DEL,GOI,BOM,COK,None

30.After completing all data cleaning and feature engineering, separate the
dataset into X (independent variables) and y (target variable), where Price
is the target.