# Pandas Method Task

# Easy Level

Q1
Load the dataset and display the first 10 records.

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

Q2
Display the last 15 customers.

In [4]:
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Q3
Show 7 random customer records.

In [5]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7572,7573,15567919,Lazarev,586,Germany,Male,37,8,167735.69,2,0,1,104665.79,0
7644,7645,15613673,Lung,675,France,Male,28,9,0.00,1,1,0,134110.93,0
4236,4237,15669945,Jackson,492,France,Male,35,4,141359.37,2,1,0,39519.53,0
6987,6988,15577170,Manfrin,532,France,Male,60,5,76705.87,2,0,1,13889.73,0
3285,3286,15627220,Kang,735,Germany,Female,43,9,98807.45,1,0,0,184570.04,1
5309,5310,15778696,Ikemefuna,684,Spain,Female,36,5,174180.39,1,1,0,119830.08,0
6821,6822,15704209,Noble,802,France,Female,39,7,120145.96,2,0,1,59497.01,1

Q4
Print complete dataset information and identify:
• Total columns
• Data type of each column
• Missing values

In [6]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Q5
Find missing values in every column.

In [12]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Q6
Display only numerical columns.

In [14]:
df.select_dtypes(include="number")

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

Q7
Generate the statistical summary of numerical columns.

In [15]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

Q8
Find duplicate rows and print how many exist.

In [17]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

Q9
Remove duplicate rows and store the cleaned dataset.

In [21]:
duplicates=df.drop_duplicates(inplace = True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [22]:
duplicates=df.drop_duplicates().sum()
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Q10
Count how many customers have exited and how many have not exited.

In [24]:
df["Exited"].value_counts(dropna = False)

Exited
0    7963
1    2037
Name: count, dtype: int64

In [25]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

# Medium Level

Q11
Rename the following columns:
CustomerId → Customer_ID
CreditScore → Credit_Score
EstimatedSalary → Salary
Exited → Churn

In [30]:
df.rename(columns={"CustomerId" : "Customer_ID",
                   "CreditScore" : "Credit_Score",
                   "EstimatedSalary" : "Salary",
                   "Exited":"Churn"} ,inplace=True)
                   
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Churn'],
      dtype='object')

In [5]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

Q12
Add the prefix
Bank_
to every column name.

In [6]:
df=df.add_prefix("Bank_")
df

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

Q13
Convert the Age column into float datatype.

In [8]:
df['Age']=df['Age'].astype(float)
print(df['Age'].dtype)

float64

Q14
Convert the Exited column into string datatype.

In [9]:
df['Exited']=df['Exited'].astype(str)
print(df['Exited'].astype)

<bound method NDFrame.astype of 0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: object>

Q15
Suppose the Balance column has missing values.
Replace them using the mean of the Balance column.

In [10]:
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
print(df['Balance'])

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

Q16
Suppose the Age column has missing values.
Replace them using the median age.

In [14]:
df["Age"]=df["Age"].fillna(df['Age'].median())
print(df['Age'].isnull().sum())

0

Q17
Display only the first five rows after renaming the columns.

In [16]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

Q18
Create a new DataFrame by dropping these columns:
RowNumber
CustomerId
Surname
Display the first 10 rows.

In [17]:
a=df.drop(columns=["RowNumber","CustomerId","Surname"])
print(a.head(10))

   CreditScore Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female  42.0       2       0.00              1
1          608     Spain  Female  41.0       1   83807.86              1
2          502    France  Female  42.0       8  159660.80              3
3          699    France  Female  39.0       1       0.00              2
4          850     Spain  Female  43.0       2  125510.82              1
5          645     Spain    Male  44.0       8  113755.78              2
6          822    France    Male  50.0       7       0.00              2
7          376   Germany  Female  29.0       4  115046.74              4
8          501    France    Male  44.0       4  142051.07              2
9          684    France    Male  27.0       2  134603.88              1

   HasCrCard  IsActiveMember  EstimatedSalary Exited
0          1               1        101348.88      1
1          0               1        112542.58      0
2          1               0        113931.57      1
3          0               0         93826.63      0
4          1               1         79084.10      0
5          1               0        149756.71      1
6          1               1         10062.80      0
7          1               0        119346.88      1
8          0               1         74940.50      0
9          1               1         71725.73      0

Q19
Drop the Geography column and display dataset information again.

In [18]:
df=df.drop(columns=["Geography"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  float64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  object
dtypes: float64(3), int64(7), object(3)
memory usage: 1015.8+ KB

Q20
Rename NumOfProducts to Products and HasCrCard to CreditCard.

In [19]:
df=df.rename(columns={
    "NumOfProducts":"Products",
    "HasCrCard":"CreditCard"})
print(df.head())

   RowNumber  CustomerId   Surname  CreditScore  Gender   Age  Tenure  \
0          1    15634602  Hargrave          619  Female  42.0       2
1          2    15647311      Hill          608  Female  41.0       1
2          3    15619304      Onio          502  Female  42.0       8
3          4    15701354      Boni          699  Female  39.0       1
4          5    15737888  Mitchell          850  Female  43.0       2

     Balance  Products  CreditCard  IsActiveMember  EstimatedSalary Exited
0       0.00         1           1               1        101348.88      1
1   83807.86         1           0               1        112542.58      0
2  159660.80         3           1               0        113931.57      1
3       0.00         2           0               0         93826.63      0
4  125510.82         1           1               1         79084.10      0

# Hard Level

Q21 (Real Company Task)
Your manager wants cleaner column names.
Rename every column as follows:
RowNumber → Row_No
CustomerId → Customer_ID
Surname → Last_Name
CreditScore → Credit_Score
Geography → Country
Gender → Sex
EstimatedSalary → Salary
Exited → Target
Display the first five rows.

In [20]:
df=df.rename(columns={
    "RowNumber":"Row_No",
    "Customerld":"Customer_ID",
    "Surname":"Last_Name",
    "CreditScore":"Credit_Score",
    "Geography":"Country",
    "Gender":"Sex",
    "EsimatedSalary":"Salary",
    "Exited":"Target"})
print(df.head(5))
df

   Row_No  CustomerId Last_Name  Credit_Score     Sex   Age  Tenure  \
0       1    15634602  Hargrave           619  Female  42.0       2
1       2    15647311      Hill           608  Female  41.0       1
2       3    15619304      Onio           502  Female  42.0       8
3       4    15701354      Boni           699  Female  39.0       1
4       5    15737888  Mitchell           850  Female  43.0       2

     Balance  Products  CreditCard  IsActiveMember  EstimatedSalary Target
0       0.00         1           1               1        101348.88      1
1   83807.86         1           0               1        112542.58      0
2  159660.80         3           1               0        113931.57      1
3       0.00         2           0               0         93826.63      0
4  125510.82         1           1               1         79084.10      0

,Row_No,CustomerId,Last_Name,Credit_Score,Sex,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Target
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Q22
Create a new DataFrame that contains only numeric columns.
Then generate its statistical summary.

In [7]:
numeric_df=df.select_dtypes(include='number')
print(numeric_df.head())
print(numeric_df.describe())

   RowNumber  CustomerId  CreditScore  Age  Tenure    Balance  NumOfProducts  \
0          1    15634602          619   42       2       0.00              1
1          2    15647311          608   41       1   83807.86              1
2          3    15619304          502   42       8  159660.80              3
3          4    15701354          699   39       1       0.00              2
4          5    15737888          850   43       2  125510.82              1

   HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          1               1        101348.88       1
1          0               1        112542.58       0
2          1               0        113931.57       1
3          0               0         93826.63       0
4          1               1         79084.10       0
         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

       EstimatedSalary        Exited
count     10000.000000  10000.000000
mean     100090.239881      0.203700
std       57510.492818      0.402769
min          11.580000      0.000000
25%       51002.110000      0.000000
50%      100193.915000      0.000000
75%      149388.247500      0.000000
max      199992.480000      1.000000

Q23.Your company received duplicate customer records.
Tasks:
• Count duplicates.
• Remove duplicates.
• Display dataset information after cleaning.

In [8]:
duplicate_count=df.duplicated().sum()
remove_duplicates=df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

Q24
Management wants every column name to begin with
Customer_
Apply this transformation using the appropriate method.

In [9]:
df=df.add_prefix("Customer_")
df.head()

,Customer_RowNumber,Customer_CustomerId,Customer_Surname,Customer_CreditScore,Customer_Geography,Customer_Gender,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_EstimatedSalary,Customer_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Q25
After renaming the columns, convert
Age
Balance
Salary
to float datatype.
Print dataset information.

In [13]:
df['Customer_Age']=df['Customer_Age'].astype(float)
df['Customer_Balance']=df['Customer_Balance'].astype(float)
df['Customer_EstimatedSalary']=df['Customer_EstimatedSalary'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_RowNumber        10000 non-null  int64
 1   Customer_CustomerId       10000 non-null  int64
 2   Customer_Surname          10000 non-null  object
 3   Customer_CreditScore      10000 non-null  int64
 4   Customer_Geography        10000 non-null  object
 5   Customer_Gender           10000 non-null  object
 6   Customer_Age              10000 non-null  float64
 7   Customer_Tenure           10000 non-null  int64
 8   Customer_Balance          10000 non-null  float64
 9   Customer_NumOfProducts    10000 non-null  int64
 10  Customer_HasCrCard        10000 non-null  int64
 11  Customer_IsActiveMember   10000 non-null  int64
 12  Customer_EstimatedSalary  10000 non-null  float64
 13  Customer_Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [14]:
df.columns

Index(['Customer_RowNumber', 'Customer_CustomerId', 'Customer_Surname',
       'Customer_CreditScore', 'Customer_Geography', 'Customer_Gender',
       'Customer_Age', 'Customer_Tenure', 'Customer_Balance',
       'Customer_NumOfProducts', 'Customer_HasCrCard',
       'Customer_IsActiveMember', 'Customer_EstimatedSalary',
       'Customer_Exited'],
      dtype='object')

In [18]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Q26
Assume CreditScore contains missing values.
Replace them with the median CreditScore.

In [20]:
df["CreditScore"] = df["CreditScore"].fillna(df["CreditScore"].median())
print(df['CreditScore'].isnull().sum())

0

Q27
Assume EstimatedSalary contains missing values.
Replace them with the mean salary.
Then print the first eight rows.

In [21]:
df["EstimatedSalary"] = df["EstimatedSalary"].fillna(df["EstimatedSalary"].mean())
print(df['EstimatedSalary'].isnull().sum())
df.head(8)

0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

Q28 (Data Cleaning Challenge)
Perform all the following:
• Remove duplicate rows.
• Rename Exited to Target.
• Convert Target to string.
• Display dataset information.

In [22]:
df.drop_duplicates(inplace=True)
df.rename(columns={"Exited":"Target"}, inplace=True)
df["Target"] = df["Target"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Target           10000 non-null  object
dtypes: float64(2), int64(8), object(4)
memory usage: 1.1+ MB

Q29 (Transformation Challenge)
Create a copy of the dataset.
Perform these transformations:
• Rename Gender to CustomerGender
• Rename Geography to Country
• Add prefix Bank_
• Remove RowNumber
• Display first 10 rows

In [23]:
df_copy = df.copy()
df_copy.rename(columns={"Gender":"CustomerGender","Geography":"Country"}, inplace=True)
df_copy = df_copy.add_prefix("Bank_")
df_copy.drop(columns=["Bank_RowNumber"], inplace=True)
df_copy.head(10)

,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Country,Bank_CustomerGender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Target
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

Q30 Real Industry Mini Project
Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
Perform all of these steps:
1. Load the dataset.
2. Display dataset information.
3. Check missing values.
4. Remove duplicate rows.
5. Rename the following columns:
o CustomerId → Customer_ID
o CreditScore → Credit_Score
o EstimatedSalary → Salary
o Exited → Target
6. Convert:
o Age → float
o Balance → float
o Target → string
7. Replace missing values:
o Age → median
o Balance → mean
8. Remove:
o RowNumber
o Surname
9. Display:
o First 10 rows
o Statistical summary
o Value counts of Target
o Final dataset information

In [24]:
df.info()
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
}, inplace=True)
df["Age"] = df["Age"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.drop(columns=["RowNumber", "Surname"], inplace=True)
print(df.head(10))
print(df.describe())
print(df["Target"].value_counts())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Target           10000 non-null  object
dtypes: float64(2), int64(8), object(4)
memory usage: 1.1+ MB
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Target             0
dtype: int64
   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82
5     15574012           645     Spain    Male  44.0       8  113755.78
6     15592531           822    France    Male  50.0       7       0.00
7     15656148           376   Germany  Female  29.0       4  115046.74
8     15792365           501    France    Male  44.0       4  142051.07
9     15592389           684    France    Male  27.0       2  134603.88

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0              1          1               1  101348.88      1
1              1          0               1  112542.58      0
2              3          1               0  113931.57      1
3              2          0               0   93826.63      0
4              1          1               1   79084.10      0
5              2          1               0  149756.71      1
6              2          1               1   10062.80      0
7              4          1               0  119346.88      1
8              2          0               1   74940.50      0
9              1          1               1   71725.73      0
        Customer_ID  Credit_Score           Age        Tenure        Balance  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000   10000.000000
mean   1.569094e+07    650.528800     38.921800      5.012800   76485.889288
std    7.193619e+04     96.653299     10.487806      2.892174   62397.405202
min    1.556570e+07    350.000000     18.000000      0.000000       0.000000
25%    1.562853e+07    584.000000     32.000000      3.000000       0.000000
50%    1.569074e+07    652.000000     37.000000      5.000000   97198.540000
75%    1.575323e+07    718.000000     44.000000      7.000000  127644.240000
max    1.581569e+07    850.000000     92.000000     10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember         Salary
count   10000.000000  10000.00000    10000.000000   10000.000000
mean        1.530200      0.70550        0.515100  100090.239881
std         0.581654      0.45584        0.499797   57510.492818
min         1.000000      0.00000        0.000000      11.580000
25%         1.000000      0.00000        0.000000   51002.110000
50%         1.000000      1.00000        1.000000  100193.915000
75%         2.000000      1.00000        1.000000  149388.247500
max         4.000000      1.00000        1.000000  199992.480000
Target
0    7963
1    2037
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB

# Bonus Challenge (Create New Columns)

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

B1
Create a new column:
TotalMoney = Balance + EstimatedSalary

In [7]:
df["TotalMoney"] = df["Balance"] + df["EstimatedSalary"]
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney,DoubleScore
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88,1238
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44,1216
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37,1004
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63,1398
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92,1700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64,1542
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38,1032
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58,1418
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83,1544
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57,1584

B2
Create a new column:
DoubleScore = CreditScore × 2

In [8]:
df["DoubleScore"] = df["CreditScore"] * 2
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney,DoubleScore
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88,1238
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44,1216
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37,1004
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63,1398
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92,1700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64,1542
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38,1032
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58,1418
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83,1544
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57,1584

B3
Create a new column:
AgeAfter10Years = Age + 10

In [9]:
df["AgeAfter10Years"] = df["Age"] + 10
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney,DoubleScore,AgeAfter10Years
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88,1238,52
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63,1398,49
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64,1542,49
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38,1032,45
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58,1418,46
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83,1544,52
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57,1584,38

B4
Create a new column:
HasBalance = Balance
Replace missing values in this new column using the mean.

In [10]:
df["HasBalance"] = df["Balance"]
df["HasBalance"] = df["HasBalance"].fillna(df["HasBalance"].mean())
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney,DoubleScore,AgeAfter10Years,HasBalance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88,1238,52,0.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51,83807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52,159660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63,1398,49,0.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53,125510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64,1542,49,0.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38,1032,45,57369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58,1418,46,0.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83,1544,52,75075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57,1584,38,130142.79

B5
Create a new column:
SalaryInLakhs = EstimatedSalary / 100000

In [11]:
df["SalaryInLakhs"] = df["EstimatedSalary"] / 100000

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney,DoubleScore,AgeAfter10Years,HasBalance,SalaryInLakhs
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88,1238,52,0.00,1.013489
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51,83807.86,1.125426
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52,159660.80,1.139316
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63,1398,49,0.00,0.938266
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53,125510.82,0.790841