# Pandas Challenges

Challenge 1 – Complete Data Cleaning
Your manager gives you a messy dataset.
Perform all of the following:
• Load the dataset.
• Display dataset information.
• Find missing values.
• Remove duplicate rows.
• Fill missing values:
o Age → median
o Balance → mean
• Rename:
o Target → CustomerStatus
o AnnualIncome → Income
• Display the first 15 rows.

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [4]:
df.isnull()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,True,False,False
1017,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,True,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,True,False,False,False,True,False

In [5]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [6]:
df["Age"]=df["Age"].fillna(df['Age'].median())
print(df['Age'].isnull().sum())

0

In [7]:
df["Balance"]=df["Balance"].fillna(df['Balance'].mean())
print(df['Balance'].isnull().sum())

0

In [11]:
df=df.rename(columns={"Target" : "CustomerStatus",
                      "AnnualIncome" : "Income"})
df.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

Challenge 2 – Banking Report
The bank wants a numeric report.
Tasks
• Select only numeric columns.
• Display summary statistics.
• Convert Age and CreditScore to float.
• Display information again.

In [12]:
numeric_df=df.select_dtypes(include='number')
print(numeric_df.head())
print(numeric_df.describe())

   CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure
0       10001  58.0   49184.0      2139          581   97523.535666       2
1       10002  65.0  162964.0      6197          732    6356.540000       1
2       10003  56.0   26956.0     37281          503  143203.920000       8
3       10004  55.0   92926.0       925          463  139627.880000       5
4       10005  66.0  108236.0      7198          394   75985.460000       5
         CustomerID          Age         Income      Spending  CreditScore  \
count   1020.000000  1020.000000     967.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112505.928645  25232.615686   602.659804
std      288.022115    15.136428   52303.362541  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   66149.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    57.000000  158000.500000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1020.000000  1020.000000
mean    97523.535666     5.261765
std     54382.357541     3.185330
min       547.600000     0.000000
25%     52145.757500     2.000000
50%     97523.535666     5.000000
75%    142086.700000     8.000000
max    199885.880000    10.000000

In [13]:
df['Age']=df['Age'].astype(float)
df['CreditScore']=df['CreditScore'].astype(float)

In [14]:
df['Age']
df['CreditScore']

0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             1020 non-null   float64
 2   Income          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   float64
 5   Balance         1020 non-null   float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  CustomerStatus  1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [5]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

Challenge 3 – Duplicate Investigation
Find duplicate customers.
Then
• Count duplicate rows.
• Remove duplicates.
• Print information before and after removing duplicates.
• Show the last 20 rows.

In [8]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.info()
df.tail(20)

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
980,10981,41.0,199633.0,8498,847,173390.59,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541,59484.58,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334,NaN,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732,175352.25,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730,120423.19,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488,126031.27,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621,115161.87,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720,158528.46,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884,44897.43,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773,39653.24,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452,17812.25,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764,165451.49,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594,149288.61,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493,83666.20,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

Challenge 4 – HR Department
HR wants better column names.
Rename
CustomerID → Employee_ID
Age → EmployeeAge
Gender → EmployeeGender
AnnualIncome → Salary
Target → PromotionStatus
Then
• Add prefix
HR_
to every column.
Display 10 random records.

In [9]:
df=df.rename(columns={
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"})
df

,Employee_ID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [10]:
df=df.add_prefix("HR_")
df

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [11]:
df.sample(10)

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
722,10723,59.0,22184.0,4864,697,132074.57,10,France,Female,Retail,Stay
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay
138,10139,35.0,22122.0,37588,350,182123.39,7,UK,Male,SME,Churn
757,10758,29.0,62293.0,44546,591,122217.95,9,Germany,Other,Retail,Stay
350,10351,19.0,141011.0,46923,514,87690.99,4,France,NaN,Corporate,Stay
608,10609,20.0,159311.0,33486,420,18637.99,10,USA,Other,SME,Churn
190,10191,20.0,34913.0,24665,593,15346.20,1,Germany,Other,SME,Churn
617,10618,46.0,62413.0,7071,519,101668.71,5,Germany,Other,SME,Stay
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
378,10379,31.0,174120.0,45663,659,172209.74,9,France,Female,Retail,Stay

In [16]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

Challenge 5 – Finance Cleaning
Finance department reports missing values.
Tasks
Fill
AnnualIncome → Median
Balance → Mean
Age → Median
Then
Generate descriptive statistics.

In [17]:
df['AnnualIncome']=df['AnnualIncome'].fillna(df['AnnualIncome'].median())
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
df['Age']=df['Age'].fillna(df['Age'].median())
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

Challenge 6 – Data Type Audit
The company says
Age and AnnualIncome are stored incorrectly.
Tasks
Convert
Age → int
AnnualIncome → float
Balance → float
Target → string
Print information.

In [20]:
df['Age']=df['Age'].astype(int)
df['AnnualIncome']=df['AnnualIncome'].astype(float)
df['Balance']=df['Balance'].astype(float)
df['Target']=df['Target'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int32
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int32(1), int64(4), object(4)
memory usage: 83.8+ KB

In [36]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [37]:
df.columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment', 'Target'],
      dtype='object')

Challenge 7 – Customer Analytics
Create a new DataFrame that
• removes Segment
• removes Geography
• removes duplicate rows
Display
• first 10 rows
• dataset information
• statistical summary

In [38]:
new_df=df.drop(columns=["Segment","Geography"])
new_df=new_df.drop_duplicates()
new_df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Gender,Target
0,10001,58.0,49184.0,2139,581,NaN,2,Male,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,Male,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Male,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,Male,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,Other,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,Other,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,Other,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,Female,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,Other,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,Female,Churn

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [40]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [55]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

Challenge 8 – ML Dataset Preparation
Prepare a machine learning dataset.
Perform
• Remove duplicates
• Remove CustomerID
• Remove Segment
• Fill missing values
• Rename Target to Output
Finally
Display
head()
info()
describe()
value_counts(Output)

In [56]:
df=df.drop_duplicates()
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [57]:
df=df.drop(columns=["CustomerID","Segment"])
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Target
0,58.0,49184.0,2139,581,NaN,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.54,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.88,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.46,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34.0,81731.0,40980,761,181465.65,5,Germany,Other,Stay
996,47.0,42475.0,1176,780,26640.99,5,France,Female,Stay
997,31.0,120531.0,46929,733,147220.82,4,India,Male,Stay
998,21.0,33661.0,22314,540,94186.48,5,NaN,Other,Stay
999,63.0,31930.0,851,559,100908.40,6,UK,Female,Stay

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

In [4]:
numeric_cols=df.select_dtypes(include="number").columns
df[numeric_cols]=df[numeric_cols].fillna(df[numeric_cols].mean())

In [5]:
df[numeric_cols]

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
0,10001,58.0,49184.000000,2139,581,97523.535666,2
1,10002,65.0,162964.000000,6197,732,6356.540000,1
2,10003,56.0,26956.000000,37281,503,143203.920000,8
3,10004,55.0,92926.000000,925,463,139627.880000,5
4,10005,66.0,108236.000000,7198,394,75985.460000,5
...,...,...,...,...,...,...,...
1015,10450,43.0,173620.000000,7121,644,60353.030000,2
1016,10753,25.0,54490.000000,13794,303,124512.070000,4
1017,10810,49.0,82062.000000,47170,813,53850.090000,8
1018,10267,38.0,112505.928645,10424,722,138100.050000,6
1019,10059,62.0,97504.000000,36833,430,97523.535666,10

In [58]:
df=df.rename(columns={
    "Target":"Output"})
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58.0,49184.0,2139,581,NaN,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.54,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.88,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.46,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34.0,81731.0,40980,761,181465.65,5,Germany,Other,Stay
996,47.0,42475.0,1176,780,26640.99,5,France,Female,Stay
997,31.0,120531.0,46929,733,147220.82,4,India,Male,Stay
998,21.0,33661.0,22314,540,94186.48,5,NaN,Other,Stay
999,63.0,31930.0,851,559,100908.40,6,UK,Female,Stay

In [59]:
df.head()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58.0,49184.0,2139,581,NaN,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.54,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.88,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.46,5,UK,Other,Churn

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           950 non-null    float64
 1   AnnualIncome  950 non-null    float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       950 non-null    float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    object
 7   Gender        950 non-null    object
 8   Output        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB

In [61]:
df.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,950.000000,950.000000,1000.000000,1000.000000,950.000000,1000.000000
mean,44.212632,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,15.524244,52409.868404,14211.735656,176.605486,55845.536430,3.179155
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.000000,65922.500000,13213.000000,441.000000,50003.880000,2.000000
50%,44.000000,112347.500000,24901.000000,606.500000,95174.625000,5.000000
75%,58.000000,157973.000000,37960.250000,758.250000,144198.130000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [8]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

In [18]:
df.value_counts()

CustomerID  Age   AnnualIncome  Spending  CreditScore  Balance    Tenure  Geography  Gender  Segment    Target
10643       41.0  125012.0      18825     761          35977.85   2       Germany    Other   Retail     Stay      2
10417       70.0  40417.0       37956     681          23880.19   10      India      Male    Retail     Stay      2
10756       53.0  74430.0       3705      489          29651.23   10      UK         Male    Retail     Churn     2
10910       66.0  118506.0      6296      306          81892.13   4       Canada     Male    SME        Churn     2
10200       19.0  115052.0      20741     484          190233.86  5       Canada     Male    Retail     Churn     2
                                                                                                                 ..
10338       36.0  84605.0       47234     375          16407.60   2       Canada     Other   SME        Churn     1
10339       27.0  122137.0      21253     669          21310.18   0       UK         Female  Corporate  Churn     1
10340       66.0  90717.0       7199      435          17459.45   6       Canada     Other   SME        Churn     1
10341       50.0  126966.0      7269      326          17923.77   8       India      Other   SME        Churn     1
10998       31.0  120531.0      46929     733          147220.82  4       India      Male    SME        Stay      1
Name: count, Length: 742, dtype: int64

In [11]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

Challenge 9 – Column Transformation
Create these new columns
NetWorth = Balance + AnnualIncome
AgeAfterRetirement = Age + 20
DoubleCreditScore = CreditScore * 2
IncomePerMonth = AnnualIncome / 12
Then
Display first 15 rows.

In [65]:
df["NetWorth"]=df["Balance"]+df["AnnualIncome"]
df["AgeAfterRetirement"]=df["Age"]+20
df["DoubleCreditScore"]=df["CreditScore"]*2
df["IncomePerMonth"]=df["AnnualIncome"]/12
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

Challenge 10 – Company Report
Display
• first five rows
• last five rows
• ten random rows
• dataset information
• descriptive statistics
Finally rename
Target → Customer_Status

In [66]:
df.head(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667

In [67]:
df.tail(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,63.0,1288,14468.333333
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,45.0,606,4540.833333
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,69.0,1626,6838.500000
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,58.0,1444,NaN
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,82.0,860,8125.333333

In [68]:
df.sample(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
146,10147,32.0,143594.0,2140,874,65601.26,9,USA,Other,Retail,Stay,209195.26,52.0,1748,11966.166667
301,10302,20.0,193066.0,27975,316,48133.26,1,India,Other,Retail,Churn,241199.26,40.0,632,16088.833333
909,10910,66.0,118506.0,6296,306,81892.13,4,Canada,Male,SME,Churn,200398.13,86.0,612,9875.500000
156,10157,18.0,113911.0,16093,631,3156.22,4,India,NaN,SME,Churn,117067.22,38.0,1262,9492.583333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
474,10475,51.0,129994.0,7874,724,29928.46,9,Germany,Other,Retail,Stay,159922.46,71.0,1448,10832.833333
490,10491,40.0,140323.0,17014,523,93339.60,10,Germany,Other,Corporate,Stay,233662.60,60.0,1046,11693.583333
595,10596,24.0,156674.0,42021,580,166974.45,4,Germany,Other,SME,Stay,323648.45,44.0,1160,13056.166667
43,10044,31.0,109884.0,13842,570,101081.81,4,India,Male,SME,Stay,210965.81,51.0,1140,9157.000000
900,10901,69.0,168172.0,48245,752,67736.89,1,France,NaN,Retail,Churn,235908.89,89.0,1504,14014.333333

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 970 non-null    float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             969 non-null    float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Target              1020 non-null   object
 11  NetWorth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

In [70]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000,920.000000,970.000000,1020.000000,967.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765,209641.594380,64.249485,1205.319608,9375.494054
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330,74287.727616,15.521935,353.121379,4358.613545
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,38.000000,600.000000,1685.583333
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000,156965.307500,50.250000,881.500000,5512.416667
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,209204.760000,64.000000,1214.000000,9363.166667
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000,261256.997500,78.000000,1514.500000,13166.708333
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,90.000000,1800.000000,16663.916667

In [71]:
df=df.rename(columns={
    "Target":"Customer_Status"})
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,233973.03,63.0,1288,14468.333333
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,179002.07,45.0,606,4540.833333
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,135912.09,69.0,1626,6838.500000
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,NaN,58.0,1444,NaN
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,NaN,82.0,860,8125.333333

Challenge 11 – Missing Value Report
Create a report showing
• Total missing values
• Numerical columns
• Mean of Balance
• Median of Age
• Fill missing values
• Display information again

In [72]:
df.isnull().sum()

CustomerID              0
Age                    50
AnnualIncome           53
Spending                0
CreditScore             0
Balance                51
Tenure                  0
Geography              51
Gender                 52
Segment                51
Customer_Status         0
NetWorth              100
AgeAfterRetirement     50
DoubleCreditScore       0
IncomePerMonth         53
dtype: int64

In [19]:
df.select_dtypes(include=['number'])

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

In [77]:
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
df['Age']=df['Age'].fillna(df['Age'].mean())
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay,233973.03,63.0,1288,14468.333333
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn,179002.07,45.0,606,4540.833333
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay,135912.09,69.0,1626,6838.500000
1018,10267,38.0,NaN,10424,722,138100.050000,6,Germany,Other,Corporate,Stay,NaN,58.0,1444,NaN
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn,NaN,82.0,860,8125.333333

In [20]:
numeric_cols=df.select_dtypes(include="number").columns
df[numeric_cols]=df[numeric_cols].fillna(df[numeric_cols].mean())

In [21]:
df[numeric_cols]

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
0,10001,58.0,49184.000000,2139,581,97523.535666,2
1,10002,65.0,162964.000000,6197,732,6356.540000,1
2,10003,56.0,26956.000000,37281,503,143203.920000,8
3,10004,55.0,92926.000000,925,463,139627.880000,5
4,10005,66.0,108236.000000,7198,394,75985.460000,5
...,...,...,...,...,...,...,...
1015,10450,43.0,173620.000000,7121,644,60353.030000,2
1016,10753,25.0,54490.000000,13794,303,124512.070000,4
1017,10810,49.0,82062.000000,47170,813,53850.090000,8
1018,10267,38.0,112505.928645,10424,722,138100.050000,6
1019,10059,62.0,97504.000000,36833,430,97523.535666,10

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   float64
 2   AnnualIncome        967 non-null    float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Customer_Status     1020 non-null   object
 11  NetWorth            920 non-null    float64
 12  AgeAfterRetirement  970 non-null    float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      967 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

In [22]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

Challenge 12 – Customer Classification
Count
Stay

Churn
Then
Rename
Target → Customer_Class
Convert it into string.

In [23]:
df["Target"].value_counts()

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [24]:
df.rename(columns={
    'Target':'Customer_Class'
},inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [25]:
df=df.astype(str)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   object
 1   Age             1020 non-null   object
 2   AnnualIncome    1020 non-null   object
 3   Spending        1020 non-null   object
 4   CreditScore     1020 non-null   object
 5   Balance         1020 non-null   object
 6   Tenure          1020 non-null   object
 7   Geography       1020 non-null   object
 8   Gender          1020 non-null   object
 9   Segment         1020 non-null   object
 10  Customer_Class  1020 non-null   object
dtypes: object(11)
memory usage: 87.8+ KB

In [30]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

Challenge 13 – Sales Department
Rename
Balance → AccountBalance
AnnualIncome → Salary
CreditScore → Score
Add prefix
Sales_
Then
Display
sample(20)

In [31]:
df=df.rename(columns={
    "Balance":"AccountBalance",
    "AnnualIncome":"Salary",
    "CreditScore":"Score"})
df

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [32]:
df=df.add_prefix("Sales_")
df

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [83]:
df.sample(20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Customer_Status,Sales_NetWorth,Sales_AgeAfterRetirement,Sales_DoubleCreditScore,Sales_IncomePerMonth
835,10836,49.000000,72604.0,40496,702,35688.430000,7,NaN,Male,SME,Stay,108292.43,69.0,1404,6050.333333
585,10586,39.000000,145817.0,30833,756,71748.320000,4,Canada,Other,Retail,Stay,217565.32,59.0,1512,12151.416667
1007,10756,53.000000,74430.0,3705,489,29651.230000,10,UK,Male,Retail,Churn,104081.23,73.0,978,6202.500000
282,10283,18.000000,108371.0,19834,881,134880.230000,3,USA,Other,SME,Stay,243251.23,38.0,1762,9030.916667
774,10775,20.000000,91171.0,27623,388,99410.890000,3,UK,Female,Corporate,Churn,190581.89,40.0,776,7597.583333
307,10308,68.000000,157484.0,21388,726,81651.840000,4,Canada,Male,SME,Stay,239135.84,88.0,1452,13123.666667
860,10861,66.000000,161485.0,33762,524,92843.200000,10,France,Male,Corporate,Stay,254328.20,86.0,1048,13457.083333
1008,10417,70.000000,40417.0,37956,681,23880.190000,10,India,Male,Retail,Stay,64297.19,90.0,1362,3368.083333
961,10962,44.249485,171569.0,6708,644,54672.990000,9,Germany,Female,Corporate,Stay,226241.99,NaN,1288,14297.416667
483,10484,21.000000,NaN,2667,767,10111.860000,5,France,Male,Corporate,Churn,NaN,41.0,1534,NaN
543,10544,51.000000,32732.0,36756,743,167763.220000,7,Germany,Male,SME,Stay,200495.22,71.0,1486,2727.666667
868,10869,26.000000,139993.0,47674,498,126404.220000,4,NaN,Female,Retail,Churn,266397.22,46.0,996,11666.083333
346,10347,69.000000,106387.0,29350,642,97523.535666,10,Germany,Male,Corporate,Stay,NaN,89.0,1284,8865.583333
187,10188,49.000000,141622.0,49943,877,97523.535666,7,France,Other,SME,Stay,NaN,69.0,1754,11801.833333
839,10840,50.000000,NaN,31835,746,80782.550000,1,Germany,Male,Retail,Churn,NaN,70.0,1492,NaN
368,10369,38.000000,50896.0,16135,612,23389.780000,5,France,Male,SME,Stay,74285.78,58.0,1224,4241.333333
30,10031,46.000000,164264.0,6916,351,130428.980000,8,India,Male,NaN,Churn,294692.98,66.0,702,13688.666667
904,10905,50.000000,123395.0,13243,802,63551.560000,9,Germany,Male,SME,Stay,186946.56,70.0,1604,10282.916667
661,10662,46.000000,100705.0,24471,722,51961.410000,4,India,Male,SME,Stay,152666.41,66.0,1444,8392.083333
264,10265,32.000000,33462.0,38741,791,34102.410000,10,France,Other,Corporate,Stay,67564.41,52.0,1582,2788.500000

In [40]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

Challenge 14 – Interview Challenge
Without creating another DataFrame,
perform
• remove duplicates
• rename Target
• fill missing values
• convert Balance to float
• display summary

In [34]:
df.drop_duplicates(inplace=True)
df

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [36]:
df.rename(columns={
    "Target": "CustomerID"
    }, inplace=True)
df

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [37]:
numeric_cols=df.select_dtypes(include="number").columns
df[numeric_cols]=df[numeric_cols].fillna(df[numeric_cols].mean())

In [38]:
df[numeric_cols]

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure
0,10001,58.0,49184.0,2139,581,97557.565779,2
1,10002,65.0,162964.0,6197,732,6356.540000,1
2,10003,56.0,26956.0,37281,503,143203.920000,8
3,10004,55.0,92926.0,925,463,139627.880000,5
4,10005,66.0,108236.0,7198,394,75985.460000,5
...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5
996,10997,47.0,42475.0,1176,780,26640.990000,5
997,10998,31.0,120531.0,46929,733,147220.820000,4
998,10999,21.0,33661.0,22314,540,94186.480000,5
999,11000,63.0,31930.0,851,559,100908.400000,6

In [41]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")

In [43]:
df.columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment', 'Target'],
      dtype='object')

In [45]:
df["Balance"]=df["Balance"].astype(str)

In [47]:
df["Balance"]

0             nan
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          nan
Name: Balance, Length: 1020, dtype: object

In [48]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,10.000000

In [50]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 15 – Data Engineer Task
Load the dataset.
Create another DataFrame containing only numeric columns.
Drop
CustomerID
Target
Display summary.

In [52]:
new_df = df.select_dtypes(include="number")

In [53]:
new_df.drop(columns=["CustomerID", "Target"], inplace=True, errors="ignore")

In [54]:
print(new_df.describe())

              Age   AnnualIncome      Spending  CreditScore        Balance  \
count  970.000000     967.000000   1020.000000  1020.000000     969.000000
mean    44.249485  112505.928645  25232.615686   602.659804   97523.535666
std     15.521935   52303.362541  14219.393105   176.560690   55796.562543
min     18.000000   20227.000000    537.000000   300.000000     547.600000
25%     30.250000   66149.000000  13134.750000   440.750000   50077.860000
50%     44.000000  112358.000000  24798.000000   607.000000   95100.060000
75%     58.000000  158000.500000  37956.000000   757.250000  143947.810000
max     70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1020.000000
mean      5.261765
std       3.185330
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000

In [55]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 16 – Mixed Cleaning
Perform
drop_duplicates()
fillna()
astype()
rename()
head()
info()
using only one DataFrame variable.

In [56]:
df.drop_duplicates(inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].astype(int)
df["Balance"] = df["Balance"].astype(float)
df.rename(columns={"Target": "Output"}, inplace=True)
print(df.head())
df.info()

   CustomerID  Age  AnnualIncome  Spending  CreditScore        Balance  \
0       10001   58       49184.0      2139          581   97557.565779
1       10002   65      162964.0      6197          732    6356.540000
2       10003   56       26956.0     37281          503  143203.920000
3       10004   55       92926.0       925          463  139627.880000
4       10005   66      108236.0      7198          394   75985.460000

   Tenure Geography Gender    Segment Output
0       2    France   Male        SME   Stay
1       1       USA   Male        SME  Churn
2       8    Canada   Male  Corporate   Stay
3       5       NaN   Male     Retail  Churn
4       5        UK  Other  Corporate  Churn
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int32
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Output        1000 non-null   object
dtypes: float64(2), int32(1), int64(4), object(4)
memory usage: 89.8+ KB

In [57]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 17 – Real Company Dataset
Manager asks
Remove duplicate records

Fill missing values
Rename all business columns
Add company prefix
Display summary
Display target counts

In [59]:
df.drop_duplicates(inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [61]:
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [63]:
categorical_cols = df.select_dtypes(include="object").columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,India,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,India,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,SME,Stay

In [64]:
df.rename(columns={"Target": "Customer_Status"}, inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,India,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,India,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,SME,Stay

In [65]:
df = df.add_prefix("Company_")
print(df.describe())
print(df["Company_Customer_Status"].value_counts())

       Company_CustomerID  Company_Age  Company_AnnualIncome  \
count         1000.000000  1000.000000           1000.000000
mean         10500.500000    44.212632         112458.303158
std            288.819436    15.130763          51081.475249
min          10001.000000    18.000000          20227.000000
25%          10250.750000    31.000000          68437.250000
50%          10500.500000    44.212632         112458.303158
75%          10750.250000    57.000000         155570.750000
max          11000.000000    70.000000         199967.000000

       Company_Spending  Company_CreditScore  Company_Balance  Company_Tenure
count       1000.000000          1000.000000      1000.000000     1000.000000
mean       25285.558000           603.088000     97557.565779        5.241000
std        14211.735656           176.605486     54430.062006        3.179155
min          537.000000           300.000000       547.600000        0.000000
25%        13213.000000           441.000000     52074.240000        2.000000
50%        24901.000000           606.500000     97557.565779        5.000000
75%        37960.250000           758.250000    142297.910000        8.000000
max        49995.000000           900.000000    199885.880000       10.000000
Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

Challenge 18 – Customer Summary
Generate
Mean Balance
Median Balance
Mean Age
Median AnnualIncome

Then
fill missing values using these statistics.

In [67]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [68]:
mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
mean_age = df["Age"].mean()
median_income = df["AnnualIncome"].median()
print(mean_balance)
print(median_balance)
print(mean_age)
print(median_income)
df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)
print(df.isnull().sum())

97523.53566563467
95100.06
44.24948453608248
112358.0
CustomerID       0
Age              0
AnnualIncome     0
Spending         0
CreditScore      0
Balance          0
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

Challenge 19 – Transformation Challenge
Create
Income_in_Lakhs
Balance_in_Lakhs

SeniorCitizen
HighCreditScore
where
SeniorCitizen = Age + 0
HighCreditScore = CreditScore * 1
(No conditional statements.)

In [69]:
df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000
df["Balance_in_Lakhs"] = df["Balance"] / 100000
df["SeniorCitizen"] = df["Age"] + 0
df["HighCreditScore"] = df["CreditScore"] * 1
df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,0.49184,0.975235,58.0,581
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay,0.31390,1.072456,69.0,770
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn,1.82141,0.384577,58.0,891
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay,0.95861,1.732967,67.0,538
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay,0.62638,0.419014,41.0,663
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn,1.79680,1.068280,22.0,475

Challenge 20 – Final Interview Project
Your manager gives you a dirty customer dataset.
Prepare the final dataset.
Requirements
Load dataset
Check information
Find missing values
Remove duplicates
Rename
CustomerID
AnnualIncome
CreditScore
Target
Convert
Age
AnnualIncome
Balance

Fill missing values
Remove
Segment
CustomerID
Create new columns
TotalMoney = Balance + AnnualIncome
AgeAfter5Years = Age + 5
MonthlyIncome = AnnualIncome / 12
CreditScoreDouble = CreditScore * 2Display
• Head
• Tail
• Sample
• Describe
• Target counts
• Final information

In [70]:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [ ]:
df.info()
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
}, inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)
df["Income"] = df["Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Income"] = df["Income"].fillna(df["Income"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.drop(columns=["Segment", "Customer_ID"], inplace=True)
df["TotalMoney"] = df["Balance"] + df["Income"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["Income"] / 12
df["CreditScoreDouble"] = df["Credit_Score"] * 2
print("First 5 Rows:")
print(df.head())
print("Last 5 Rows:")
print(df.tail())
print("Random Sample:")
print(df.sample(10))
print("Statistical Summary:")
print(df.describe())
print("Customer Status Counts:")
print(df["Customer_Status"].value_counts())
print("Final Dataset Information:")
df.info()