In [2]:
import pandas as pd
# load the datasets
df = pd.read_csv("C:\\Users\\harit\\Downloads\\dataset.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
#Problem 1:
import pandas as pd
# load the datasets
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Problem 2:
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [8]:
# Problem 3:
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# Problem 4:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2668,2669,15582325,Jennings,524,France,Male,52,2,87894.26,1,1,0,173899.42,1
3291,3292,15635893,T'ien,693,France,Female,28,8,0.00,2,1,1,158545.25,0
1322,1323,15598846,Shahan,700,France,Female,44,2,58781.76,1,1,0,16874.92,0
4911,4912,15691004,Yu,407,Spain,Male,37,1,0.00,1,1,1,49161.12,1
8795,8796,15716608,Walker,651,Spain,Male,38,2,0.00,3,1,0,67029.82,1
6494,6495,15752846,Pinto,699,France,Male,28,7,0.00,2,1,1,22684.78,0
1296,1297,15803365,Coffee,653,Spain,Male,55,2,70263.83,1,0,1,62347.71,0
1546,1547,15727944,Simpkinson,701,Germany,Female,48,1,92072.68,1,1,1,133992.36,0
536,537,15592846,Fiorentini,639,Germany,Male,35,10,128173.90,2,1,0,59093.39,0
222,223,15727829,McIntyre,567,France,Male,42,2,0.00,2,1,1,167984.61,0

In [7]:
# Problem 5:
df.shape
# How many rows are there
df.shape[0]
# How many columns are there
df.shape[1]

14

In [9]:
# Problem 6:
# Number of non null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [15]:
# Data types
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [19]:
# Memory Usage 
df.memory_usage()

Index                132
RowNumber          80000
CustomerId         80000
Surname            80000
CreditScore        80000
Geography          80000
Gender             80000
Age                80000
Tenure             80000
Balance            80000
NumOfProducts      80000
HasCrCard          80000
IsActiveMember     80000
EstimatedSalary    80000
Exited             80000
dtype: int64

In [20]:
df.memory_usage().sum()

1120132

In [11]:
# Problem 7:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
# Problem 8:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [21]:
# Problem 9:
df.isnull().sum()
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [15]:
# Problem 10:
df.CreditScore

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [16]:
# Problem 11:
df[["CustomerId", "Surname", "Balance", "Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [17]:
# Problem 12:
df.select_dtypes(include=['number'])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [18]:
# Problem 13:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [19]:
#Problem 14:
print(df.duplicated().sum())
df=df.drop_duplicates()

0

In [20]:
# Problem 15:
import pandas as pd
df = pd.read_csv("C:\\Users\\harit\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

# Operators + Loops

In [22]:
# Problem 1:
a=int(input("Enter first number"))
b=int(input("Enter second number"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("FloorDivision:",a//b)
print("Modulus:",a%b)
if a>b:
    print("a is greater than b:",a)
elif b>a:
    print("b is greater than a:",b)

else:
    print("Both are equal")

Enter first number 20
Enter second number 24

Addition: 44
Subtraction: -4
Multiplication: 480
Division: 0.8333333333333334
FloorDivision: 0
Modulus: 20
b is greater than a: 24

In [23]:
# Problem 2:
for i in range(1,51):
    if i==40:
        break
    if i % 5 == 0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

In [24]:
# Problem 3
total=0
count=0
while True:
    n=int(input("Enter number:"))
    if n<0:
        break
    total+=n
    count+=1
if count>0:
    avg=total/count
    print("Sum :", total)
    print("Average :", avg)
else:
    print("No Positive Number")

Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Enter number: 5
Enter number: 6
Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Enter number: -2

Sum : 31
Average : 3.1

In [25]:
# Problem 4
for i in range(5,0,-1):
    for j in range(i):
        print("*",end="")
    print()

*****
****
***
**
*

In [26]:
#Problem 5
# using for loop
n=int(input("Enter number:"))
fact=1
for i in range(1, n+1):
    fact=fact*i
print("Factorial=",fact)

Enter number: 5

Factorial= 120

In [27]:
# using while loop
n=int(input("Enter number:"))
fact=1
i=1
while i<=n:
    fact=fact*i
    i+=1
print("Factorial=",fact)

Enter number: 8

Factorial= 40320

# Data Types & Methods

In [28]:
# Problem 6:
s="Haritha"
print(s.upper())
print(s.count('a'))
print(s.replace("","-"))
if s.startswith("Hello"):
    print("String starts with Hello")
else:
    print("String does not start with Hello")

HARITHA
2
-H-a-r-i-t-h-a-
String does not start with Hello

In [29]:
# Problem 7:
lists=[1,2,3,4,5,6]
print(lists)
lists.insert(7,8)
print(lists)
lists.remove(3)
print(lists)
lists.pop()
print(lists)
lists.sort(reverse=True)
print(lists)
lists.reverse()
print(lists)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 8]
[1, 2, 4, 5, 6, 8]
[1, 2, 4, 5, 6]
[6, 5, 4, 2, 1]
[1, 2, 4, 5, 6]

In [31]:
# Problem 8:
s={"Haritha":85,"Akshitha":90,"Varshini":95}
print("Students who scored more than 80")
for name,marks in s.items():
    if marks > 80:
        print(name, ":",marks)

Students who scored more than 80
Haritha : 85
Akshitha : 90
Varshini : 95

In [32]:
# Problem 9:
s1={1,2,3,4}
s2={3,4,5,6}
print("set1:",s1)
print("set2:",s2)
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
s1.add(7)
print(s1)
s1.discard(3)
print(s1)

set1: {1, 2, 3, 4}
set2: {3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{1, 2, 3, 4, 7}
{1, 2, 4, 7}

# OOP + Encapsulation

In [38]:
# Problem 10:
class Student:
    def __init__(self, marks):
        self.__marks=0

    def get_marks(self):
        return self.__marks

    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks=marks
        else:
            print("Marks  should be between 0 and 100")
            
s=Student(55)
s.set_marks(85)
print("Marks:", s.get_marks())

Marks: 85

In [40]:
# Problem 11:
class InsufficientBalanceError(Exception):
    pass
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount
        print("Deposited:", amount)
        print("Balance:", self.__balance)

    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise InsufficientBalanceError("Balance cannot be negative.")
        self.__balance -= amount
        print("Withdrawn:", amount)
        print("Balance:", self.__balance)

account = BankAccount(5000)
account.deposit(1000)
try:
    account.withdraw(2000)
    account.withdraw(5000)
except InsufficientBalanceError as e:
    print(e)

Deposited: 1000
Balance: 6000
Withdrawn: 2000
Balance: 4000
Balance cannot be negative.

In [43]:
# Problem 12:
class Employee:
    company_name = "IBM"

    def __init__(self, name):
        self.name = name
emp1 = Employee("Haritha")
emp2 = Employee("Akshitha")
print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)
Employee.company_name = "Wipro"
print("\nAfter updating company_name:\n")
print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)

Haritha works at IBM
Akshitha works at IBM

After updating company_name:

Haritha works at Wipro
Akshitha works at Wipro

In [44]:
# Problem 13:
class Product:
    def __init__(self, price):
        self.__price = 200
        self.set_price(price)

    def get_price(self):
        return self.__price

    def set_price(self, price):
        if price >= 200:
            self.__price = price
        else:
            print("Price must be at least 200.")
p = Product(800)
print("Price:", p.get_price())
p.set_price(900)
print("Updated Price:", p.get_price())
p.set_price(160)
print("Final Price:", p.get_price())

Price: 800
Updated Price: 900
Price must be at least 200.
Final Price: 900

In [46]:
# Problem 14:
class Rectangle:
    def __init__(self, length, width):
        self.__length = length
        self.__width = width
    def area(self):
        return self.__length * self.__width

    def perimeter(self):
        return 2 * (self.__length + self.__width)
r = Rectangle(2, 4)
print(r.area())
print(r.perimeter())

8
12

In [47]:
# Problem 15:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
class Student(Person):
    def __init__(self, name, age, course):
        super().__init__(name, age)   
        self.course = course
    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course:", self.course)
s = Student("Haritha", 22, "DS")
s.display()

Name: Haritha
Age: 22
Course: DS

In [48]:
# Problem 16:
class Person:
    def show(self):
        print("Person")
class Employee(Person):
    def show(self):
        print("Employee")
class Manager(Employee):
    def show(self):
        print("Manager")
m = Manager()
m.show()

Manager

In [49]:
# Problem 17:
class Animal:
    def sound(self):
        print("Animals make sounds")
class Dog(Animal):
    def sound(self):
        print("Dog barks")
class Cat(Animal):
    def sound(self):
        print("Cat meows")
d = Dog()
c = Cat()
d.sound()
c.sound()

Dog barks
Cat meows

In [50]:
#Problem 18:
from abc import ABC, abstractmethod
class Shape(ABC):
    def __init__(self):
        print("Shape Constructor")
    @abstractmethod
    def area(self):
        pass
class Circle(Shape):
    def __init__(self, radius):
        super().__init__()   
        self.radius = radius
    def area(self):
        return 3.14 * self.radius * self.radius
class Square(Shape):
    def __init__(self, side):
        super().__init__()   
        self.side = side
    def area(self):
        return self.side * self.side
c = Circle(5)
s = Square(4)
print( c.area())
print(s.area())

Shape Constructor
Shape Constructor
78.5
16

In [51]:
# Problem 19
class Father:
    def show(self):
        print("Father")
class Mother:
    def show(self):
        print("Mother")
class Child(Father, Mother):
    def show(self):
        print("Method conflict resolved:")
        Father.show(self)      
        Mother.show(self)      

c = Child()
c.show()

Method conflict resolved:
Father
Mother