# 20 data cleaning practice questions

#Basic Exploration & Missing Values

1. How many missing values are there in each column? Which column has the highest
number of missing values?

In [47]:
import pandas as pd
df=pd.read_csv("C:\\Users\\harit\\Downloads\\Customer_datasets - Customer_datasets.csv")
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,FALSE
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,FALSE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

In [35]:
df.isnull().sum()

Customer_ID            0
Name                 135
Age                   80
Salary                96
Join_Date            244
Department            50
Performance_Score     38
Email                 48
City                  43
Gender                34
Is_Active             25
dtype: int64

2. What percentage of rows have at least one missing value?

In [36]:
missing_values=df.isnull().any(axis=1).sum()
total=len(df)
per=(missing_values/total)*100
per

34.90276356192426

3. Drop all rows that have more than 3 missing values. How many rows remain?

In [43]:
missing_values=df.isnull().sum(axis=1)
df.drop(df[missing_values > 3].index)
len(df)

2030

#Duplicates

4. How many exact duplicate rows are present in the dataset?

In [42]:
df.duplicated().sum()

30

5. How many duplicate Customer_IDs are there? Keep only the first occurrence of each
Customer_ID.

In [44]:
df['Customer_ID'].duplicated().sum()
df.drop_duplicates(subset="Customer_ID",keep="first",inplace=True)
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2023,1725,Customer_1725,69,41999.16,2019-11-01,Operations,45.7,user1724@outlook.com,Chicago,Other,FALSE
2024,1096,Customer_1096,74,43331.22,2016-09-10 00:00:00,Finance,92.2,user1095@gmail.com,San Antonio,Male,TRUE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

#Age Column

6. Convert the Age column to numeric. How many values could not be converted
(became NaN)?

In [54]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"]

0       27.0
1       27.0
2       62.0
3        NaN
4       41.0
        ...
2025    74.0
2026    72.0
2027    21.0
2028    69.0
2029    65.0
Name: Age, Length: 2030, dtype: float64

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\harit\\Downloads\\Customer_datasets - Customer_datasets.csv")
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,FALSE
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,FALSE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

7. After converting Age to numeric, identify and remove outliers using the IQR method.
How many outliers were removed?

In [55]:
Q3 = df["Age"].quantile(0.75)
Q1 = df["Age"].quantile(0.25)
IQR  = Q3 - Q1
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR
outlier = df[(df['Age'] < lower_bound) | (df['Age'] > upper_bound)]
outlier

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
175,439,Customer_439,200.0,NaN,13/01/2020,Operations,80.3,user438@gmail.com,San Jose,Male,TRUE
240,271,Customer_271,999.0,35552.47,2016-04-30,Sales,65.4,user270@gmail.com,Chicago,Other,FALSE
571,498,Customer_498,200.0,46843.31,2020-04-21,Finance,NaN,user497@yahoo.com,San Diego,Male,FALSE
766,1654,Customer_1654,200.0,74080.88,03/05/2018,Marketing,67.4,user1653@outlook.com,New York,NaN,FALSE
870,842,Customer_842,200.0,50921.32,2021-07-25,Marketing,41.4,user841@company.com,Houston,Male,FALSE
1221,146,Customer_146,150.0,51147.85,2018-02-16,Finance,8.9,user145@outlook.com,Los Angeles,Female,FALSE
1357,1371,Customer_1371,150.0,42419.66,NaN,Sales,79.1,user1370@yahoo.com,Chicago,Male,TRUE
1375,1770,Customer_1770,200.0,55658.1,2020-02-15,Operations,61,user1769@company.com,Philadelphia,Other,FALSE
1485,488,Customer_488,999.0,55423.04,2018-08-11,Financ,78.1,user487@company.com,Los Angeles,Other,TRUE
1862,726,Customer_726,200.0,68135.74,NaN,Operations,61.4,user725@yahoo.com,San Antonio,Male,TRUE
1902,1181,Customer_1181,999.0,69427.82,12-03-2018,Operations,77.3,user1180@outlook.com,San Antonio,Male,FALSE

8. Replace remaining missing values in Age with the median age.

In [59]:
df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
df["Age"]=df["Age"].median()
df["Age"]

0       50.0
1       50.0
2       50.0
3       50.0
4       50.0
        ...
2025    50.0
2026    50.0
2027    50.0
2028    50.0
2029    50.0
Name: Age, Length: 2030, dtype: float64

#Salary Column

9. Clean the Salary column: remove currency symbols ($), commas, and convert
everything possible to numeric. How many values remained non-numeric?

In [63]:
df["Salary"] = df["Salary"].str.replace("$", "")
df["Salary"] = df["Salary"].str.replace(",", "")
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
print("Non-numeric values:", df["Salary"].isnull().sum())

Non-numeric values: 122

10. After cleaning, find the mean and median salary. Which one is more affected by
outliers?

In [68]:
mean=df["Salary"].mean()
median=df["Salary"].median()
print(mean)
print(median)

59293.07900900904
59293.07900900902

#Date Column

11. Convert the Join_Date column to proper datetime format. How many dates failed to
parse?

In [73]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"].isnull().sum()

944

12. Extract the year from the cleaned Join_Date. What is the most common joining year?

In [6]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Year"] = df["Join_Date"].dt.year
df["Year"].mode()[0]

1970.0

#Categorical Columns (Inconsistencies)

13. Standardize the Department column (fix casing, trim spaces, fix common typos like
“Sale” → “Sales”, “Financ” → “Finance”, etc.). How many unique departments remain
after cleaning?

In [8]:
df['Department']=df['Department'].str.strip().str.title()
df['Department']=df['Department'].replace({
    "Sale" : "Sales",
    "Financ" : "Finance"})
df['Department'].nunique()

11

14. Clean the City column (standardize names, fix “Los Angles” → “Los Angeles”, “NY” →
“New York”, “Philly” → “Philadelphia”, etc.). List the final unique cities.

In [9]:
df['City']=df['City'].str.strip().str.title()
df['City']=df['City'].replace({
    "Los Angles" : "Los Angeles",
    "NY" : "New York",
    "Philly" : "Philadelphia"})
df['City'].unique()

array(['Houston', 'Dallas', nan, 'New York', 'San Antonio', 'Los Angeles',
       'San Diego', 'Chicago', 'Houston Tx', 'San Jose', 'Philadelphia',
       'Phoenix', 'Ny', 'Unknown'], dtype=object)

15. Standardize the Gender column so it only contains “Male”, “Female”, and “Other”.
How many records were changed?

In [10]:
original = df['Gender'].copy()
df['Gender'] = df['Gender'].str.strip().str.title()
df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'F': 'Female',
    'Man': 'Male',
    'Woman': 'Female'
})
changed = (original != df['Gender']).sum()
changed

62

#Performance_Score & Is_Active

16. Convert Performance_Score to numeric. Replace non-numeric values with NaN, then
fill missing scores with the mean.

In [11]:
df['Performance_Score'] = pd.to_numeric(df['Performance_Score'], errors='coerce')
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].mean())
df['Performance_Score']

0       69.10000
1        1.90000
2       78.20000
3       85.80000
4       82.50000
          ...
2025    46.80000
2026    51.67763
2027    43.70000
2028    17.50000
2029    47.40000
Name: Performance_Score, Length: 2030, dtype: float64

17. Clean the Is_Active column so it becomes a proper boolean (True/False). Map values
like “Yes”, “Y”, “1”, “Active”, “true” → True and “No”, “N”, “0”, “Inactive”, “false” →
False.

In [12]:
df['Is_Active'] = df['Is_Active'].astype(str).str.strip().str.lower()
df['Is_Active'] = df['Is_Active'].map({
    'yes': True,
    'y': True,
    '1': True,
    'active': True,
    'true': True,
    
    'no': False,
    'n': False,
    '0': False,
    'inactive': False,
    'false': False
})
df['Is_Active']
df['Is_Active'].unique()
df['Is_Active'].value_counts()

Is_Active
False    1031
True      974
Name: count, dtype: int64

#Email & Name

18. Flag invalid email addresses (those that do not contain “@” or have incomplete
domains). How many invalid emails are there?

19. Clean the Name column: replace empty strings, “N/A”, and “Unknown” with NaN.
How many names are still missing after this step?

In [13]:
import numpy as np
df['Name'] = df['Name'].replace(['', 'N/A', 'Unknown'], np.nan)
df['Name'].isna().sum()

155

#Final Challenge

20. Perform a complete data cleaning pipeline on the entire dataset and save the
cleaned version as cleaned_dataset.csv. Report the final shape of the cleaned dataset
and briefly describe the main cleaning steps you applied.